name: Build and Deploy Docker Container to Azure Web App - openclassrooms-projet8-api-segmentation

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Récupérer le code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Installer et configurer Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # 3. Se connecter à l'ACR
      - name: Login to Azure Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.ACR_LOGIN_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      # 4. Construire et pousser l'image Docker
      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.ACR_LOGIN_SERVER }}/openclassrooms-projet8-api-segmentation:latest .
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/openclassrooms-projet8-api-segmentation:latest

      # 5. Se connecter à Azure
      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # 6. Déployer l'image sur la Web App Azure
      - name: Deploy to Azure Web App for Containers
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'openclassrooms-projet8-api-segmentation'
          slot-name: 'Production'
          images: '${{ secrets.ACR_LOGIN_SERVER }}/openclassrooms-projet8-api-segmentation:latest'
